$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1a2k.pdb 1A2K A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1a2k.pdb 1A2K B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1eer.pdb 1EER A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1ffw.pdb 1FFW A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1i2m.pdb 1I2M A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1i2m.pdb 1I2M B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1ib1.pdb 1IB1 A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1ib1.pdb 1IB1 B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1k5d.pdb 1K5D A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1k5d.pdb 1K5D B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1k5d.pdb 1K5D C
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1ktz.pdb 1KTZ A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1kxp.pdb 1KXP A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1kxp.pdb 1KXP D
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1pvh.pdb 1PVH B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1rlb.pdb 1RLB A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1rlb.pdb 1RLB B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1rlb.pdb 1RLB C
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1rlb.pdb 1RLB D
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1rlb.pdb 1RLB E
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 1s1q.pdb 1S1Q B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 2btf.pdb 2BTF A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 2btf.pdb 2BTF P
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 2hqs.pdb 2HQS A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 2nyz.pdb 2NYZ A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 2nyz.pdb 2NYZ B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 2nyz.pdb 2NYZ D
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 3bp8.pdb 3BP8 A
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 3bp8.pdb 3BP8 B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 3bzd.pdb 3BZD B
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 3cph.pdb 3CPH G
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 3szk.pdb 3SZK D
$HOME/projects/enzyme_distance/scripts/tacc/run_pipeline.sh 3szk.pdb 3SZK E
